### ISSUE TITLE
Why does the executable in the snap differ from the one in the tarball?

### ISSUE THREAD

**Issue by hsivonen** [snapcrafters/sublime-text#16]
The `sublime_text` executable in `sublime-text_3170_amd64.snap` has sha256 5322e659171dbd32d8716e787e214066cdc851f8408e31ed8a62b4f20f273b57. The sublime_text executable in upstream `sublime_text_3_build_3170_x64.tar.bz2` has sha256 117f1729d79ec4e85a6e0a971b3b3d919304e57957c5c0c9c88768a678e6ebb6.

Why?

(The `crash_reporter` and `plugin_host` binaries differ, too.)

**Comment by kyluca** [comment]
Yup I just tried to reproduce the problem and got the same hashes as you @hsivonen... :frowning_face:

When I did a fresh `sudo snap install sublime-text`, it gave me build 3170 from revision 9 ([build link here](https://build.snapcraft.io/user/snapcrafters/sublime-text/211220)).

The snapcraft.yaml has since been updated to build the snap with support for multiple archs, and the snap for build 3170 was rebuilt as revision 12 ([build link here](https://build.snapcraft.io/user/snapcrafters/sublime-text/213695)). Although that revision hasn't yet been published to the `stable` channel (must get it via `sudo snap install --edge sublime-text` for now).

Unfortunately, even that revision still seems to differ with the sha256 of `/snap/sublime-text/12/opt/sublime-text/sublime-text` being `d406ff9d3cae5ed8af344e17ef8db59fb66d088c2c92804e2438d9812b5b715d`.

**Comment by wbond** [comment]
This is kind of a huge issue @flexiondotorg and @om26er. We’ve been seeing bug reports about crashes on Linux and a common thread is this snap package.

The idea that a third-party is distributing modified versions of Sublime Text is a huge blow to the suitability of the snap platform, and rather reinforces my current opinion that we need to retain 100% control over the distribution of our software.

Please:

 - Immediately replace the modified version of Sublime Text with a non-modified version
 - Explain how the binaries were modified
 - How this was allowed to happen
 - How we can be assured this won’t happen again

**Comment by hsivonen** [comment]
[Indeed ELF patching seems to be part of what snapcraft does.](https://insights.ubuntu.com/2018/02/01/snapcraft-summit-summary-day-2)

**Comment by popey** [comment]
Hi @hsivonen @wbond. Sincere apologies for this causing you a support headache and concerns over the platform.

Just to confirm, we are indeed using `patchelf` to modifiy binaries inside the snap. We've found this is necessary to ensure classic-confined snaps load system libraries from the correct location. In some cases a non-patched binary will in fact crash more than a patched one. 

I've build patched and non-patched snaps locally, and confirm that the non-patched ones match your original tarball contents.

```
alan@hal:~/src/sublime-text$ sha256sum patchelf/opt/sublime_text/sublime_text
563799ee26211fd6f1d5e62faee64b337a5c34e23b8bfedd258a2ddeb7ef0c53  patchelf/opt/sublime_text/sublime_text
alan@hal:~/src/sublime-text$ sha256sum nopatchelf/opt/sublime_text/sublime_text
1673775ba0eb1160fb1e83fc47ee60c1029cf52d83bbd9f3c8e70e46dfc975db  nopatchelf/opt/sublime_text/sublime_text
alan@hal:~/src/sublime-text$ sha256sum upstream/sublime_text_3/sublime_text
1673775ba0eb1160fb1e83fc47ee60c1029cf52d83bbd9f3c8e70e46dfc975db  upstream/sublime_text_3/sublime_text
```

As you can see @om26er has offered a patch to disable patchelf. I'll merge that and push to the store now.

Finally, @wbond if you'd rather take ownership of this snap (which currently has ~15K active installs) we can organise that. We're keen for upstreams to own their own snaps, and can walk someone on your team through the process.

**Comment by popey** [comment]
I have pushed revision 18 and 19 to the amd64/i386 stable channels respectively. Installed on my laptop and here's the sha256sum of the subl binary.

```
alan@hal:~$ sha256sum /snap/sublime-text/current/opt/sublime_text/sublime_text
1673775ba0eb1160fb1e83fc47ee60c1029cf52d83bbd9f3c8e70e46dfc975db  /snap/sublime-text/current/opt/sublime_text/sublime_text
```
